export const list = {
    "1": { "name": "Piper Cub", "dir": "|models|aircraft|cub|", "multiplayerFiles": "", "path": "/models/aircraft/cub/" },
    "2": { "name": "Cessna 172", "dir": "|models|aircraft|premium|cessna_172|", "multiplayerFiles": "", "path": "/models/aircraft/premium/cessna_172/" },
    "3": { "name": "Alphajet PAF", "dir": "|models|aircraft|premium|alphajet_paf|", "multiplayerFiles": "multiplayer.gltf,multiplayer-low.glb", "path": "/models/aircraft/premium/alphajet_paf/" },
    "4": { "name": "Boeing 737-700", "dir": "|models|aircraft|premium|737_700|", "multiplayerFiles": "multiplayer.gltf,multiplayer-low.glb", "path": "/models/aircraft/premium/737_700/" },
    "5": { "name": "Embraer Phenom 100", "dir": "|models|aircraft|premium|phenom_100|", "multiplayerFiles": "multiplayer.gltf,multiplayer-low.glb", "path": "/models/aircraft/premium/phenom_100/" },
    "6": { "name": "de Havilland DHC6 Twin Otter", "dir": "|models|aircraft|premium|dhc6|", "multiplayerFiles": "multiplayer.gltf,multiplayer-low.glb", "path": "/models/aircraft/premium/dhc6/" },
    "7": { "name": " F-16 Fighting Falcon", "dir": "|models|aircraft|premium|f16|", "multiplayerFiles": "multiplayer.gltf,multiplayer-low.gltf", "path": "/models/aircraft/premium/f16/" },
    "8": { "name": "Pitts Special S1", "dir": "|models|aircraft|premium|pitts|", "multiplayerFiles": "multiplayer.gltf,multiplayer-low.gltf", "path": "/models/aircraft/premium/pitts/" },
    "16": { "name": "Douglas DC-3", "dir": "|models|aircraft|dc3|", "multiplayerFiles": "", "path": "/models/aircraft/dc3/" },
    "17": { "name": "McDonnell Douglas MD-11", "dir": "|models|aircraft|md11|", "multiplayerFiles": "", "path": "/models/aircraft/md11/" },
    "18": { "name": "Sukhoi Su-35", "dir": "|models|aircraft|su35|", "multiplayerFiles": "", "path": "/models/aircraft/su35/" },
    "19": { "name": "Airbus A380", "dir": "|models|aircraft|a380|", "multiplayerFiles": "", "path": "/models/aircraft/a380/" },
    "20": { "name": "Concorde", "dir": "|models|aircraft|concorde|", "multiplayerFiles": "", "path": "/models/aircraft/concorde/" },
    "21": { "name": "Zlin Z-50", "dir": "|models|aircraft|zlin|", "multiplayerFiles": "", "path": "/models/aircraft/zlin/" },
    "22": { "name": "Cessna 152", "dir": "|models|aircraft|cessna|", "multiplayerFiles": "", "path": "/models/aircraft/cessna/" },
    "26": { "name": "Antonov An-140", "dir": "|models|aircraft|AN140|", "multiplayerFiles": "", "path": "/models/aircraft/AN140/" },
    "40": { "name": "Evektor Sportstar", "dir": "|models|aircraft|sportstar|", "multiplayerFiles": "", "path": "/models/aircraft/sportstar/" },
    "41": { "name": "szd-48-3 Jantar", "dir": "|models|aircraft|jantar|", "multiplayerFiles": "", "path": "/models/aircraft/jantar/" },
    "50": { "name": "Paraglider", "dir": "|models|aircraft|paraglider|", "multiplayerFiles": "", "path": "/models/aircraft/paraglider/" },
    "51": { "name": "Major Tom (hot air balloon)", "dir": "|models|aircraft|tom|", "multiplayerFiles": "", "path": "/models/aircraft/tom/" },
    "52": { "name": "Hughes 269a/TH-55 Osage", "dir": "|models|aircraft|hughes|", "multiplayerFiles": "", "path": "/models/aircraft/hughes/" },
    "53": { "name": "Goat Airchair", "dir": "|models|aircraft|goat|", "multiplayerFiles": "", "path": "/models/aircraft/goat/" },
    "235": { "name": "Boeing 787-8", "dir": "|backend|aircraft|repository|GXD01E_126645_235|", "multiplayerFiles": "", "path": "/backend/aircraft/repository/GXD01E_126645_235/" },
    "236": { "name": "Embraer E190", "dir": "|backend|aircraft|repository|GXD02RZ_126645_236|", "multiplayerFiles": "", "path": "/backend/aircraft/repository/GXD02RZ_126645_236/" },
    "237": { "name": "Boeing 767-300ER", "dir": "|backend|aircraft|repository|GXD03FI_126645_237|", "multiplayerFiles": "", "path": "/backend/aircraft/repository/GXD03FI_126645_237/" },
    "238": { "name": "Boeing 757-200", "dir": "|backend|aircraft|repository|GXD04N_126645_238|", "multiplayerFiles": "", "path": "/backend/aircraft/repository/GXD04N_126645_238/" },
    "239": { "name": "Airbus A350-900", "dir": "|backend|aircraft|repository|GXD05OQ_166617_239|", "multiplayerFiles": "", "path": "/backend/aircraft/repository/GXD05OQ_166617_239/" },
    "240": { "name": "Boeing 777-300ER", "dir": "|backend|aircraft|repository|Boeing 777-300ER_933_240|", "multiplayerFiles": "", "path": "/backend/aircraft/repository/Boeing 777-300ER_933_240/" },
    "241": { "name": "FLDG Boeing 737 MAX 8", "dir": "|backend|aircraft|repository|D01_933_241|", "multiplayerFiles": "", "path": "/backend/aircraft/repository/D01_933_241/" },
    "242": { "name": "FLDG Airbus A320neo", "dir": "|backend|aircraft|repository|D02_933_242|", "multiplayerFiles": "", "path": "/backend/aircraft/repository/D02_933_242/" },
    "244": { "name": "Airbus A330-300", "dir": "|backend|aircraft|repository|A02_166635_244|", "multiplayerFiles": "", "path": "/backend/aircraft/repository/A02_166635_244/" },
    "247": { "name": "FLDG Bombardier Dash 8 Q400", "dir": "|backend|aircraft|repository|E01_166635_247|", "multiplayerFiles": "", "path": "/backend/aircraft/repository/E01_166635_247/" },
    "252": { "name": "Boeing 747-8 Freighter", "dir": "|backend|aircraft|repository|A03_166635_252|", "multiplayerFiles": "", "path": "/backend/aircraft/repository/A03_166635_252/" },
    "1000": { "name": "Boeing 787", "dir": "|models|aircraft|generics|787|", "multiplayerFiles": "", "path": "/models/aircraft/generics/787/" },
    "1001": { "name": "Boeing 73x", "dir": "|models|aircraft|generics|73x|", "multiplayerFiles": "", "path": "/models/aircraft/generics/73x/" },
    "1002": { "name": "Boeing 74x", "dir": "|models|aircraft|generics|74x|", "multiplayerFiles": "", "path": "/models/aircraft/generics/74x/" },
    "1003": { "name": "Boeing 75x", "dir": "|models|aircraft|generics|75x|", "multiplayerFiles": "", "path": "/models/aircraft/generics/75x/" },
    "1004": { "name": "Boeing 76x", "dir": "|models|aircraft|generics|76x|", "multiplayerFiles": "", "path": "/models/aircraft/generics/76x/" },
    "1005": { "name": "Boeing 77x", "dir": "|models|aircraft|generics|77x|", "multiplayerFiles": "", "path": "/models/aircraft/generics/77x/" },
    "1006": { "name": "Boeing 78x", "dir": "|models|aircraft|generics|78x|", "multiplayerFiles": "", "path": "/models/aircraft/generics/78x/" },
    "1007": { "name": "Airbus A31x", "dir": "|models|aircraft|generics|a31x|", "multiplayerFiles": "", "path": "/models/aircraft/generics/a31x/" },
    "1008": { "name": "Airbus A32x", "dir": "|models|aircraft|generics|a32x|", "multiplayerFiles": "", "path": "/models/aircraft/generics/a32x/" },
    "1009": { "name": "Airbus A33x", "dir": "|models|aircraft|generics|a33x|", "multiplayerFiles": "", "path": "/models/aircraft/generics/a33x/" },
    "1010": { "name": "Airbus A34x", "dir": "|models|aircraft|generics|a34x|", "multiplayerFiles": "", "path": "/models/aircraft/generics/a34x/" },
    "1011": { "name": "Airbus A35x", "dir": "|models|aircraft|generics|a35x|", "multiplayerFiles": "", "path": "/models/aircraft/generics/a35x/" },
    "1012": { "name": "Airbus A380", "dir": "|models|aircraft|generics|a380|", "multiplayerFiles": "", "path": "/models/aircraft/generics/a380/" },
    "1013": { "name": "ATR42", "dir": "|models|aircraft|generics|atr42|", "multiplayerFiles": "", "path": "/models/aircraft/generics/atr42/" },
    "1014": { "name": "BAE146", "dir": "|models|aircraft|generics|bae146|", "multiplayerFiles": "", "path": "/models/aircraft/generics/bae146/" },
    "1015": { "name": "CRJ 700", "dir": "|models|aircraft|generics|crj700|", "multiplayerFiles": "", "path": "/models/aircraft/generics/crj700/" },
    "1016": { "name": "CRJ 900", "dir": "|models|aircraft|generics|crj900|", "multiplayerFiles": "", "path": "/models/aircraft/generics/crj900/" },
    "1017": { "name": "Embraer 170", "dir": "|models|aircraft|generics|e170|", "multiplayerFiles": "", "path": "/models/aircraft/generics/e170/" },
    "1018": { "name": "Embraer 190", "dir": "|models|aircraft|generics|e190|", "multiplayerFiles": "", "path": "/models/aircraft/generics/e190/" },
    "1019": { "name": "Piper PA-28", "dir": "|models|aircraft|generics|pa28|", "multiplayerFiles": "", "path": "/models/aircraft/generics/pa28/" },
    "1020": { "name": "Dash 8", "dir": "|models|aircraft|generics|dh8|", "multiplayerFiles": "", "path": "/models/aircraft/generics/dh8/" },
    "1021": { "name": "Cessna Citation", "dir": "|models|aircraft|generics|c25a|", "multiplayerFiles": "", "path": "/models/aircraft/generics/c25a/" },
    "1022": { "name": "Cessna", "dir": "|models|aircraft|generics|c182|", "multiplayerFiles": "", "path": "/models/aircraft/generics/c182/" },
    "1023": { "name": "MD11", "dir": "|models|aircraft|generics|md11|", "multiplayerFiles": "", "path": "/models/aircraft/generics/md11/" },
    "1024": { "name": "Mirage 2000", "dir": "|models|aircraft|generics|mirage2000|", "multiplayerFiles": "", "path": "/models/aircraft/generics/mirage2000/" },
    "1025": { "name": "Helicopter", "dir": "|models|aircraft|generics|heli|", "multiplayerFiles": "", "path": "/models/aircraft/generics/heli/" },
    "1026": { "name": "Cirrus SR22", "dir": "|models|aircraft|generics|sr22|", "multiplayerFiles": "", "path": "/models/aircraft/generics/sr22/" },
    "1069": { "name": "Cirrus SR22 Turbo", "dir": "|backend|aircraft|repository|E02_166635_1069|", "multiplayerFiles": "", "path": "/backend/aircraft/repository/E02_166635_1069/" },
    "2003": { "name": "Boeing 737-800", "dir": "|backend|aircraft|repository|Boeing 737-800_187219_1003|", "multiplayerFiles": "", "path": "/backend/aircraft/repository/Boeing 737-800_187219_1003/" },
    "2004": { "name": "CRJ-900", "dir": "|backend|aircraft|repository|CRJ-900_187219_1004|", "multiplayerFiles": "", "path": "/backend/aircraft/repository/CRJ-900_187219_1004/" },
    "2153": { "name": "Airbus A340-600", "dir": "|backend|aircraft|repository|G5_166635_2153|", "multiplayerFiles": "", "path": "/backend/aircraft/repository/G5_166635_2153/" }
}